config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {omniauth_callbacks: 'omniauth'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'users#index'
  resources :users
  resources :logs
  resources :friends, :controller => "users", :type => "Friend"
  resources :enemies, :controller => "users", :type => "Enemy"
  resources :neutralities, :controller => "users", :type => "Neutrality"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/enemy.rb
class Enemy < User
end

app/models/friend.rb
class Friend < User
end

app/models/log.rb
class Log < ApplicationRecord
end

app/models/neutrality.rb
class Neutrality < User
end

app/models/user.rb
class User < ApplicationRecord
	# Include default devise modules. Others available are:
	# :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
	devise :database_authenticatable, :registerable,
		:recoverable, :rememberable, :validatable,
		:omniauthable, omniauth_providers: [:google_oauth2]

	validates :username, presence: true
	validates :username, uniqueness: true
	validates :type, presence: true

	def self.create_from_provider_data(provider_data)
		where(provider: provider_data.provider, uid: provider_data.uid).first_or_create do |user|
			user.email = provider_data.info.email
			user.username = provider_data.info.email
			user.type = "Neutrality"
			user.password = Devise.friendly_token[0, 20]
		end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :authenticate_user!
	before_action :configure_permitted_parameters, if: :devise_controller?

	protected

	def configure_permitted_parameters
		devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :type])
	end
end

app/controllers/logs_controller.rb
class LogsController < ApplicationController
	def index
		@logs = Log.all.order("date DESC").decorate
	end
end

app/controllers/omniauth_controller.rb
class OmniauthController < ApplicationController
	def google_oauth2
		@user = User.create_from_provider_data(request.env['omniauth.auth'])
		if @user.persisted?
			sign_in_and_redirect @user
		else
			flash[:error] = 'There was a problem signing you in through Google. Please register or try signing in later.'
			redirect_to new_user_registration_url
		end
	end

	def failure
		flash[:error] = 'There was a problem signing you in. Please register or try signing in later.'
		redirect_to new_user_registration_url
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :set_user, only: [:show, :edit, :update, :destroy]

	def index
		@users = User.all.decorate
	end

	def show
	end

	def create	
		@user = User.new(user_params)
		if @user.save
			redirect_to users_url, notice: 'User was successfully created.'
		else
			render :new
		end	
	end

	def edit		
	end

	def update
		if @user.update(user_params)
			lg = LogService.new(user_params)
			lg.create_log
			redirect_to users_url, notice: 'User was successfully updated.'
		else
			render :edit
		end
	end

	def destroy
		@user.destroy
		redirect_to users_url
	end
end

private 
def set_user
	@user = User.find(params[:id])
end

def user_params
	params.require(:user).permit(:id, :username, :type)
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/logs_helper.rb
module LogsHelper
end

app/helpers/omniauth_helper.rb
module OmniauthHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Task9</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="#">Navbar</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="/users">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/logs">Logs</a>
          </li>
        </ul>
        <p class="navbar-text float-right">

          <% if user_signed_in? %>
            Logged in as <strong><%= current_user.username %></strong>.
            <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
            <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
          <% else %>
            <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
            <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
          <% end %>
        </p>
      </div>
    </nav>
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
      <% end %>
    <%= yield %>
  </body>
</html>

app/views/logs/index.html.erb
<h1>Log</h1>

<% @logs.each do |log| %>
  <p><%= log.display_log %></p>
<% end %>

<%= link_to 'Back', users_path %>

app/views/users/_edit_form.html.erb
<%= form_for(@user, as: :user, url: user_path(@user), method: :put) do |f| %>
	<% if user.errors.any? %>
		<div id="error_explanation">
			<h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>
			<ul>
				<% user.errors.full_messages.each do |message| %>
					<li><%= message %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
	<%= @user.username %>
	<%= f.hidden_field :username, :value => @user.username %>
	<p>Change type to:</p>
	<% if @user.type == 'Friend' %>
		<%= f.select(:type, options_for_select([['Friend', 'Friend'], ['Neutrality', 'Neutrality']], selected: f.object.type), include_blank: true)%>
	<% elsif @user.type == 'Enemy' %>
		<%= f.select(:type, options_for_select([['Enemy', 'Enemy'], ['Neutrality', 'Neutrality']], selected: f.object.type), include_blank: true)%>
	<% else %>
		<%= f.select(:type, options_for_select([['Enemy', 'Enemy'], ['Friend', 'Friend']], selected: f.object.type), include_blank: true)%>
	<% end %>
	<%= f.submit %>
<% end %>

app/views/users/_new_form.html.erb
<%= form_for @user do |f| %>
	<% if user.errors.any? %>
		<div id="error_explanation">
			<h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>
			<ul>
				<% user.errors.full_messages.each do |message| %>
					<li><%= message %></li>
				<% end %>
			</ul>
		</div>
	<% end %>

	<div class="field">
		<%= f.label :email %><br />
		<%= f.email_field :email, autofocus: true, autocomplete: "email" %>
	</div>

	<div class="field">
		<%= f.label :username %><br />
		<%= f.text_field :username %>
	</div>

	<%= f.hidden_field :type, :value => 'Neutrality' %>  

	<div class="field">
		<%= f.label :password %>
		<% if @minimum_password_length %>
			<em>(<%= @minimum_password_length %> characters minimum)</em>
		<% end %><br />
		<%= f.password_field :password, autocomplete: "new-password" %>
	</div>

	<div class="field">
		<%= f.label :password_confirmation %><br />
		<%= f.password_field :password_confirmation, autocomplete: "new-password" %>
	</div>

	<div class="actions">
		<%= f.submit "Create user" %>
	</div>
<% end %>

app/views/users/edit.html.erb
<h1>Edit user</h1>

<%= render 'edit_form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>List of all users</h1>

<% @users.each do |user| %>
  <%= user.display_user %>
  <%= link_to 'Show', user %>
  <%= link_to 'Edit', edit_user_path(user) %>
  <%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %>
  </br>
<% end %>
<br>


app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'new_form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<h1>User page</h1>

<h2><%= @user.username %></h2>
<p><%= @user.type %></p>

<%= link_to 'Back', users_path %>